@startuml

class DyMainActivity<? extends AppCompatActivity>{
    -stateID
    -clickMovie()
    -clickTv()
    -clickOscar()
    -clickAnima()
}

class SearchActivity<? extend AppCompatActivity>{
    -text
    -search()
}

class PlayActivity<? extends AppCompatActivity>{
    -Url
    -webViewMainfest()
}

class ItemDetailActivity<? extends AppCompatActivity>{
    -mItem
    -play()
    -check()
}


DyMainActivity <.. SearchActivity
SearchActivity <.. ItemDetailActivity
ItemDetailActivity <.. PlayActivity

@enduml